language: php

php:
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs src --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/codecept run --env isolated --coverage-xml

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
